### ISSUE TITLE
Ladder rendered behind background.

### ISSUE THREAD

**Issue by skinnyMan** [GDCASU/Joyful#11]
The first ladder in the scene (Create-a-level part b) gets rendered behind foliage.

![image](https://cloud.githubusercontent.com/assets/4166275/13375698/cc9c64d2-dd63-11e5-96ec-d556accd4e75.png)

**Comment by etang4** [comment]
Good catch, that's just a UI Layer issue. Thanks for logging this.

**Comment by Raptorhands** [comment]
Any update on this?

**Comment by alexgryan** [comment]
@Raptorhands I'm going to look at this right now

**Comment by alexgryan** [comment]
The issue has been solved. I changed the layering of the Player and Ladder.
