### ISSUE TITLE
Anger AI acts weird in Joey Level.

### ISSUE THREAD

**Issue by etang4** [GDCASU/Joyful#23]
Randomly spazzes in place and does not take collision with player projectile (basically can't be killed).

**Comment by alexgryan** [comment]
@etang4 Just bug tested it. Excel and I got it in a working state but the Invoke("Destroy") command in the EnemyHealthManager makes Anger bug out and last momentarily after being killed. We removed the Invoke command and just Destroyed the enemy in the giveDamage method. If you have any alternatives to allow your private Destroy command let us know. We commented it out.

**Comment by etang4** [comment]
@alexgryan so was the bug ever fixed? If fixing this bug creates a new one. then we haven't fixed it o.o I can look into it later since it's in my domain.

**Comment by alexgryan** [comment]
It's done @etang4. @Excoh and I finished it.
