### ISSUE TITLE
Player is knockback in one direction only? (Joey Level with first Anger Enemy)

### ISSUE THREAD

**Issue by etang4** [GDCASU/Joyful#24]
Problem: I want to jump over an enemy but collide with the edge of the enemy but the knockback knocks the player back the other direction in an ugly and frustrating way. 
(i.e. I'm moving left and jumping over an enemy, but I collide with the rightmost edge of the enemy that knocks me left.)

Current implementation of knockback is determined by which direction the enemy is coming from (from what I understand).

We should look into determining whether knockback should be determined by which direction the player is trying to go.

**Comment by xeuorux** [comment]
On my branch it already works in this way: The player is knocked away from the enemy, regardless of which direction either of them are going.

**Comment by etang4** [comment]
Ok. Well until your changes are pushed. We'll leave this issue ticket ongoing. Once it is pushed, please close this ticket.

**Comment by etang4** [comment]
Fixed.
