### ISSUE TITLE
Player Control - Continuous Jumping 

### ISSUE THREAD

**Issue by skinnyMan** [GDCASU/Joyful#7]
Not sure if this is intended behavior or not, but holding the spacebar down makes the hero constantly jump up and down.

I checked out the design doc, all it says for jumping is "Strong Space-Player High Jump" under player controls.

**Comment by etang4** [comment]
I think that's an intended behavior @Raptorhands ?

**Comment by skinnyMan** [comment]
Talked to @Raptorhands , This is not intended behavior. I can take a look at resolving this if you guys want.

@etang4 @alexgryan

**Comment by etang4** [comment]
Nice!
